mySQLdatabase:
  url: '127.0.0.1'
  port: 3306
  name: 'demo'
  username: 'root'
  password: '1qaz!QAZ'
  type: 'mysql'
  tablePrefix: ""
  maxOpenConns: 1000
  maxIdleConns: 1000
  maxLifeTime: 5
  logMode: true
  version: "0.0.1"
postgreSQL:
  host: 'localhost'
  user: 'postgres'
  password: 'postgres'
  database: 'postgres'